### ISSUE TITLE
CpG Methylation Heatmap

### ISSUE THREAD

**Issue by ChengYunazhi** [Molmed/Nordlund-Backlin-2013#1]
Hi, reading your article has inspired me a lot, and I want to draw a heatmap for a specific set of CpG like yours, could you share r code.

All the best

Yuanzhi

<img width="824" alt="截屏2020-08-05下午5 12 14" src="https://user-images.githubusercontent.com/13846735/89394571-d0d84500-d73e-11ea-9b3e-9eb48b263ab9.png">

**Comment by backlin** [comment]
Hi,
I'm glad to hear that! I'll have a look tonight and see if I can find the plotting library that I wrote and used.

Beware though that R code does not age well (dependencies break and R itself changes) and given that it is 5 years old you will probably hit some problems running it. But we'll see.

**Comment by ChengYunazhi** [comment]
Thanks!!  
 I might be able to adjust code when encounter problems.

**Comment by backlin** [comment]
Here's the code: http://christofer.backlin.se/files/analyse450k_1.8.0_for_cheng.tar.gz (will be removed in the future)

It's an internal package for data management, browsing the data, plotting, etc. I have removed parts of it to not give away security details, names of people/projects, and code written by others (since it's not relevant and I couldn't bother asking them for permission).

You want the function `gene.plot` in `analyse450k/R/plot.r`. _Note that you need to fix a code inconsistency issue first though:_ `analyse450k` spells the annotations object `met.anot` and this repo (correctly) spells it `met.annot`. Apart from that I believe the code should work fine with the objects prepared by [process_annotations.R](https://github.com/Molmed/Nordlund-Backlin-2013/blob/master/process_annotations.R) etc., but I haven't tried it.

**Comment by ChengYunazhi** [comment]
Thank so much for your generous help, I have downloaded the code and start to try it !
